### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by jabdala1** [jabdala1/DMIT-2018-Workbook#2]
Create a page that shows our suppliers and the products they offer. I will need to see information in the following "structure"

 - **Supplier:**
   - Company Name
   - Phone Number
   - **Product Summary:**
      - Product Name
      - Category Name
      - Unit Price
      - Quantity/Unit

### Tasks
- [ ] Create LINQ query in LinqPad
- [ ] Create classes for the _Read Model_
- [ ] Copy/Adapt LinqPad query to BLL method
- [ ] Create page with nested repeater
